version: "2"

run:
  timeout: "5m"
  relative-path-mode: "gomod"

formatters:
  enable:
    - "gofumpt"
    - "goimports"

  settings:
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - "github.com/dsh2dsh/zrepl"

linters:
  enable:
    - "asciicheck"
    - "bidichk"
    - "copyloopvar"
    - "errorlint"
    - "gocritic"
    - "makezero"
    - "misspell"
    - "nilnesserr"
    - "nolintlint"
    - "perfsprint"
    - "prealloc"
    - "predeclared"
    - "revive"
    - "sloglint"
    - "testifylint"
    - "unconvert"
    - "usestdlibvars"
    - "usetesting"
    - "wastedassign"
    - "wrapcheck"

  settings:
    errcheck:
      exclude-functions:
        # List of functions to exclude from checking, where each entry is a
        # single function to exclude. See
        # https://github.com/kisielk/errcheck#excluding-functions for details.
        - "fmt.Fprint"
        - "io/ioutil.ReadFile"
        - "io.Copy(*bytes.Buffer)"
        - "io.Copy(os.Stdout)"
        - "(io.ReadCloser).Close"
        - "(net.Conn).Close"
        - "(*os.File).Close"
        - "(*github.com/fatih/color.Color).Fprintf"
        - "(*github.com/fatih/color.Color).Printf"

    nolintlint:
      # Enable to require an explanation of nonzero length after each nolint
      # directive.
      # Default: false
      require-explanation: true
      # Enable to require nolint directives to mention the specific linter being
      # suppressed.
      # Default: false
      require-specific: true

    revive:
      rules:
        - name: "time-equal"

    sloglint:
      # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#attributes-only
      # Default: false
      attr-only: true

    staticcheck:
      # https://staticcheck.dev/docs/configuration/options/#dot_import_whitelist
      # Default: ["github.com/mmcloughlin/avo/build", "github.com/mmcloughlin/avo/operand", "github.com/mmcloughlin/avo/reg"]
      dot-import-whitelist:
        - "github.com/dsh2dsh/zrepl/internal/replication/logic/diff"
        - "github.com/dsh2dsh/zrepl/internal/replication/logic/pdu"
      # SAxxxx checks in https://staticcheck.dev/docs/configuration/options/#checks
      # Example (to disable some checks): [ "all", "-SA1000", "-SA1001"]
      # Default: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
      checks:
        - "all"
        # QF1001 - Apply De Morgan’s law
        # https://staticcheck.dev/docs/checks/#QF1001
        - "-QF1001"
        - "-ST1000"
        - "-ST1003"
        # ST1005 - Incorrectly formatted error string
        # https://staticcheck.dev/docs/checks/#ST1005
        - "-ST1005"
        # Poorly chosen receiver name
        # https://staticcheck.dev/docs/checks/#ST1006
        - "-ST1006"
        # ST1012 - Poorly chosen name for error variable
        # https://staticcheck.dev/docs/checks/#ST1012
        - "-ST1012"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"

    usetesting:
      # Enable/disable `os.Setenv()` detections.
      # Default: false
      os-setenv: true

      # Enable/disable `os.TempDir()` detections.
      # Default: false
      os-temp-dir: true

    wrapcheck:
      # An array of glob patterns which, if any match the package of the function
      # returning the error, will skip wrapcheck analysis for this error. This is
      # useful for broadly ignoring packages and/or subpackages from wrapcheck
      # analysis. There are no defaults for this value.
      ignore-package-globs:
        - "encoding/*"
        - "gopkg.in/yaml.v3"
        - "github.com/dsh2dsh/zrepl/*"

  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - "errcheck"
          - "wrapcheck"
