linters:
  enable:
    - "asciicheck"
    - "bidichk"
    - "copyloopvar"
    # - "errorlint"
    # - "gocritic"
    # - "gofumpt"
    - "goimports"
    - "makezero"
    - "misspell"
    - "nolintlint"
    - "perfsprint"
    - "prealloc"
    - "revive"
    - "testifylint"
    - "unconvert"

linters-settings:
  goconst:
    # Ignore test files.
    # Default: false
    ignore-tests: true

  goimports:
    # A comma-separated list of prefixes, which, if set, checks import paths
    # with the given prefixes are grouped after 3rd-party packages.
    # Default: ""
    local-prefixes: "github.com/dsh2dsh/zrepl"

  nolintlint:
    # Enable to require an explanation of nonzero length after each nolint directive.
    # Default: false
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true

  revive:
    rules:
      - name: "time-equal"

  wrapcheck:
    # An array of glob patterns which, if any match the package of the function
    # returning the error, will skip wrapcheck analysis for this error. This is
    # useful for broadly ignoring packages and/or subpackages from wrapcheck
    # analysis. There are no defaults for this value.
    ignorePackageGlobs:
      - "github.com/dsh2dsh/zrepl/*"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - wrapcheck
    # Disable staticcheck 'Empty body in an if or else branch' as it's useful
    # to put a comment into an empty else-clause that explains why whatever
    # is done in the if-caluse is not necessary if the condition is false.
    - linters:
        - staticcheck
      text: "SA9003:"

