# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - "go mod tidy"
    - "go mod vendor"

dist: "./.build"

builds:
  - env:
      - "CGO_ENABLED=0"
    goos:
      - "freebsd"
      - "linux"
    goarch:
      - "amd64"
      - "arm64"
    ldflags:
      - "-s -w -X github.com/dsh2dsh/{{.ProjectName}}/internal/version.{{.ProjectName}}Version={{.Version}}"

archives:
  - formats: [ "tar.gz" ]
    # use zip for windows archives
    format_overrides:
      - goos: "windows"
        formats: [ "zip" ]

    files:
      - "LICENSE"
      - "README.md"
      - "dist"

release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default: false.
  prerelease: "auto"

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"

source:
  # Whether this pipe is enabled or not.
  enabled: true

  # Additional files/globs you want to add to the source archive.
  #
  # Since: v1.11
  # Templates: allowed
  files:
    - "vendor"
