jobs:
  - type: "sink"
    name: "limited_sink"
    root_fs: "fs0"
    recv:
      execpipe:
        # mbuffer | zfs recv
        - [ "/usr/local/bin/mbuffer", "-q", "-R", "16K" ]

  - type: "push"
    name: "limited_push"
    connect:
      type: "local"
      listener_name: "limited_sink"
      client_identity: "local_backup"
    datasets:
      - pattern: "root"
        recursive: true
    send:
      execpipe:
        # zfs send | mbuffer
        - [ "/usr/local/bin/mbuffer", "-q", "-r", "16K" ]
    snapshotting:
      type: "manual"
    pruning:
      keep_sender:
        - type: "last_n"
          count: 1
      keep_receiver:
        - type: "last_n"
          count: 1

  - type: sink
    name: "unlimited_sink"
    root_fs: "fs1"
