include_keys: "keys.yaml"

listen:
  - addr: ":8888"
    tls_cert: "/etc/zrepl/backups.crt"
    tls_key: "/etc/zrepl/backups.key"
    zfs: true

jobs:
  - name: "sink"
    type: "sink"
    root_fs: "storage/zrepl/sink"
