include_keys: "keys.yaml"

jobs:
  # Pull from source server A
  - name: "source_a"
    type: "pull"
    connect:
      type: "http"
      server: "https://a.example.com:8888"
      listener_name: "target_b"
      client_identity: "a.example.com"
    root_fs: "pool0/backup"
    interval: "10m"
    pruning:
      keep_sender:
        # Source does the pruning in its snap job
        - type: "regex"
          regex: ".*"
      # Receiver-side pruning can be configured as desired on each target server
      keep_receiver:
        # Keep non-zrepl snapshots
        - type: "regex"
          negate: true
          regex: '^zrepl_'
          # Time-based snapshot retention
        - type: "grid"
          grid: "1x1h(keep=all) | 24x1h | 30x1d | 12x30d"
          regex: '^zrepl_'
