include_keys: "keys.yaml"

listen:
  - addr: ":8888"
    tls_cert: "/etc/zrepl/example.com.crt"
    tls_key: "/etc/zrepl/example.com.key"
    zfs: true

jobs:
  # Separate job for snapshots and pruning
  - name: "snapshots"
    type: "snap"
    datasets:
      - pattern: "tank"           # all filesystems
        recursive: true
    snapshotting:
      type: "periodic"
      prefix: "zrepl_"
      interval: "10m"
    pruning:
      keep:
        # Keep non-zrepl snapshots
        - type: "regex"
          negate: true
          regex: '^zrepl_'
        # Time-based snapshot retention
        - type: "grid"
          grid: "1x1h(keep=all) | 24x1h | 30x1d | 12x30d"
          regex: '^zrepl_'

  # Source job for target B
  - name: "target_b"
    type: "source"
    datasets:
      - pattern: "tank"         # all filesystems
        recursive: true
    # Snapshots are handled by the separate snap job
    snapshotting:
      type: "manual"
    client_keys:
      - "a.example.com"

  # Source job for target C
  - name: "target_c"
    type: "source"
    datasets:
      - pattern: "tank"         # all filesystems
        recursive: true
    # Snapshots are handled by the separate snap job
    snapshotting:
      type: "manual"
    client_keys:
      - "a.example.com"

  # Source jobs for remaining targets.
  # ...
