include_keys: "keys.yaml"

listen:
  - addr: "192.168.122.189:8888"
    tls_cert: "/etc/zrepl/cert.pem"
    tls_key: "/etc/zrepl/key.pem"
    zfs: true

jobs:
  - type: "sink"
    name: "laptop_sink"
    root_fs: "pool2/backup_laptops"
