include_keys: "keys.yaml"

listen:
  - addr: ":8888"
    tls_cert: "/etc/zrepl/cert.pem"
    tls_key: "/etc/zrepl/key.pem"
    zfs: true

jobs:
  - name: "pull_source"
    type: "source"
    datasets:
      - pattern: ""
        recursive: true
      - pattern: "secret"
        exclude: true
    snapshotting:
      type: "periodic"
      interval: "10m"
      prefix: "zrepl_"
