jobs:
- name: pull_source
  type: source
  serve:
    type: stdinserver
    client_identities:
      - "client1"
      - "client2"
  datasets:
    - pattern: ""
      recursive: true
    - pattern: "secret"
      exclude: true
  snapshotting:
    type: periodic
    interval: 10m
    prefix: zrepl_

