# https://goreleaser.com/ci/actions/#workflow
name: "goreleaser snapshot"

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v7.0.0"
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: "actions/setup-go@v6"
        with:
          go-version-file: 'go.mod'

      - name: "Run GoReleaser"
        uses: "goreleaser/goreleaser-action@v7"
        with:
          version: "latest"
          args: "release --snapshot"

      - name: "Upload artifacts"
        if: "${{ !cancelled() }}"
        uses: "actions/upload-artifact@v7"
        with:
          name: "snapshot"
          path: ".build/zrepl_*.tar.gz"
          retention-days: 1
          compression-level: 0
          include-hidden-files: true

      - name: "Cleanup"
        run: "rm -rf .build vendor"
